version: '3.7'

services:

  sbt:
    image: hseeberger/scala-sbt:graalvm-ce-19.3.0-java8_1.3.7_2.12.10
    stdin_open: true
    network_mode: host
    ports:
      - 9680:9680
    volumes:
      - ./docker-cache/.ivy2:/home/sbtuser/.ivy2
      - ./docker-cache/.cache:/home/sbtuser/.cache
      - ./:/mnt
    working_dir: /mnt
    command: >
      sbt run -Drun.mode=Dev
      -Dhttp.port=9681
  mongo:
    image: mongo
    ports:
      - 27017:27017
