#%RAML 1.0
---
title: Push Pull Notifications Api
version: 1.0

protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: application/hal+json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/misc/push-pull-notification:
  /notifications/topics/{topicId}:
    get:
      displayName: Get a list of the notifications
      description: Returns a list of notifications that have been send to a topic
      is: [headers.acceptHeader]
      securedBy: [ sec.x-application ]
      responses:
          200:
            body:
              application/json:
                example: |
                  [
                    {
                        "notificationId": "1ed5f407-8096-40d1-87ef-9a2a103eeb85",
                        "topicId": "50dca3fc-c37c-4f03-b719-63571333624c",
                        "notificationContentType": "APPLICATION_JSON",
                        "message": "{}",
                        "status": "RECEIVED",
                        "createdDateTime": "2020-06-01T10:20:23.160+0000"
                    },
                    {
                        "notificationId": "86bb5f82-452e-49c8-88af-1f321d573960",
                        "topicId": "50dca3fc-c37c-4f03-b719-63571333624c",
                        "notificationContentType": "APPLICATION_XML",
                        "message": "<someXml>xmlValue</someXml>",
                        "status": "RECEIVED",
                        "createdDateTime": "2020-06-01T10:27:33.613+0000"
                    }
                  ]
          404:
            body:
              application/json:
                example: |
                  {
                    "code": "TOPIC_NOT_FOUND",
                    "message": "Topic Id: 50dca3fc-c37c-4f03-b719-635713336 not found"
                  }
          500:
            body:
              application/json:
                example: |
                  {
                    "code": "UNKNOWN_ERROR",
                    "message": "An Unknown Error has occurred"
                  }  
  /topics:
    get:
      displayName: Get a list of topics
      description: TODO
      queryParameters:
        topicName:
          displayName: Topic Name
          type: string
          description: Name of topic
          example: I%20am%20a%20Topic(URL Encoded)
          required: true
      is: [headers.acceptHeader]
      securedBy: [ sec.x-application ]
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                      "notificationId": "1ed5f407-8096-40d1-87ef-9a2a103eeb85",
                      "topicId": "50dca3fc-c37c-4f03-b719-63571333624c",
                      "notificationContentType": "APPLICATION_JSON",
                      "message": "{}",
                      "status": "RECEIVED",
                      "createdDateTime": "2020-06-01T10:20:23.160+0000"
                  },
                  {
                      "notificationId": "86bb5f82-452e-49c8-88af-1f321d573960",
                      "topicId": "50dca3fc-c37c-4f03-b719-63571333624c",
                      "notificationContentType": "APPLICATION_XML",
                      "message": "<someXml>xmlValue</someXml>",
                      "status": "RECEIVED",
                      "createdDateTime": "2020-06-01T10:27:33.613+0000"
                  }
                ]
        404:
          body:
            application/json:
              example: |
                {
                  "code": "TOPIC_NOT_FOUND",
                  "message": "Topic Id: 50dca3fc-c37c-4f03-b719-635713336 not found"
                }
        500:
          body:
            application/json:
              example: |
                {
                  "code": "UNKNOWN_ERROR",
                  "message": "An Unknown Error has occurred"
                }